/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AltCuidad.java
 *
 * Created on 26-nov-2009, 21:05:02
 */

package pantallas;





import entity.Localidades;
import entity.Provincias;
import java.util.Iterator;
import java.util.List;
import javax.ejb.EJB;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import servers.ServerLocator;
import sessionbeans.LocalidadesFacadeRemote;
import sessionbeans.ProvinciasFacadeRemote;





/**
 *
 * @author Cintia
 */
public class AltLocalidad extends javax.swing.JFrame {
  @EJB
  private static ProvinciasFacadeRemote provincias;
  @EJB
  private static LocalidadesFacadeRemote localidades;
  private ServerLocator servidor = new ServerLocator();
  private Localidades localidad= new Localidades();
    private final List<Localidades> list;
    /** Creates new form AltCuidad */
    public AltLocalidad(List<Localidades> lista) {

        initComponents();
        this.setAlwaysOnTop(true);
        ciudad.setVisible(true);
        codigoPostal.setVisible(true);
         try{
        provincias = (ProvinciasFacadeRemote) servidor.lookup(ProvinciasFacadeRemote.class.getName());
      }catch(NamingException ex) {
            JOptionPane.showMessageDialog(rootPane, "No se ha podido cargar el Bean  - "+ ex.getMessage() , "ERROR", 2);
            this.dispose();
        }
           try{
        localidades =  (LocalidadesFacadeRemote) servidor.lookup(LocalidadesFacadeRemote.class.getName());
      }catch(NamingException ex) {
            JOptionPane.showMessageDialog(rootPane, "No se ha podido cargar el Bean  - "+ ex.getMessage() , "ERROR", 2);
            this.dispose();
        }

         list = lista;
          Iterator iter = lista.iterator();
        while (iter.hasNext()){
        Object objeto = iter.next();
        Localidades pro = (Localidades) objeto;
        jLocalidades.addItem(pro);
        }



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscarProv = new javax.swing.JButton();
        jLocalidades = new javax.swing.JComboBox();
        cancelar = new javax.swing.JButton();
        ciudad = new javax.swing.JPanel();
        codigoPostal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tCodigoPostal = new javax.swing.JTextField();
        tArea = new javax.swing.JTextField();
        tLocalidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jProvincias = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        buscarCiu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta Cuidad");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincia"));

        jLabel1.setText("Seleccione Ciudad:");

        buscarProv.setText("Cargar");
        buscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(buscarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarProv))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        ciudad.setBorder(javax.swing.BorderFactory.createTitledBorder("Localidad"));

        jLabel3.setText("Ingrese Codigo Postal:");

        jLabel4.setText("Ingrese Codigo de Area:");

        jLabel2.setText("Ingrese Localidad: ");

        jLabel5.setText("Provincia :");

        buscarCiu.setText("Buscar");
        buscarCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCiuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout codigoPostalLayout = new javax.swing.GroupLayout(codigoPostal);
        codigoPostal.setLayout(codigoPostalLayout);
        codigoPostalLayout.setHorizontalGroup(
            codigoPostalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codigoPostalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(codigoPostalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(codigoPostalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addGroup(codigoPostalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jProvincias, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tLocalidad)
                    .addComponent(tArea, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tCodigoPostal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(buscarCiu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        codigoPostalLayout.setVerticalGroup(
            codigoPostalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, codigoPostalLayout.createSequentialGroup()
                .addGroup(codigoPostalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(buscarCiu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(codigoPostalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(codigoPostalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(codigoPostalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout ciudadLayout = new javax.swing.GroupLayout(ciudad);
        ciudad.setLayout(ciudadLayout);
        ciudadLayout.setHorizontalGroup(
            ciudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ciudadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigoPostal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ciudadLayout.setVerticalGroup(
            ciudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ciudadLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(codigoPostal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cancelar)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProvActionPerformed
        // Cargar la ciudad luego de selecionarla
        Localidades l = list.get(jLocalidades.getSelectedIndex());
        jProvincias.addItem(l.getProvinciasId());
        tLocalidad.setText(l.getNombre());
        tCodigoPostal.setText(""+l.getCodpostal());
        tArea.setText(""+l.getCodarea());
       localidad = l;

    /*   int p= provincias.buscar(tProv.getText());
        if (p > 0) {
         JOptionPane.showMessageDialog(rootPane, tProv.getText()+" ya esta en la base de datos", "Operación exitosa", 1);
         
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR: No se encuentra la Provincia", "ERROR", 0);
        }*/
      // Provincias p= provincias.getProvincias(Integer.parseInt(prov.getText()));
       // prov.setText(p.toString());
}//GEN-LAST:event_buscarProvActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // Cancela la accion y cierra la ventana
        this.dispose ();
}//GEN-LAST:event_cancelarActionPerformed

    private void buscarCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCiuActionPerformed
        // Busca todas las provincias de la base de datos
        jProvincias = new javax.swing.JComboBox();
        List<Provincias> p = provincias.ordenarAsc();
        Iterator iter = p.iterator();
        while (iter.hasNext()){
        Object objeto = iter.next();
        Provincias pro = (Provincias) objeto;
        jProvincias.addItem(pro);
        }
    /*   int resultado= localidades.buscar(c, n);
       if(resultado > 0){
       JOptionPane.showMessageDialog(rootPane, n+" ya esta en la base de datos"+resultado, "Operación exitosa", 1);
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR: No se encuentra la Localidad", "ERROR", 0);
        }
*/
        

}//GEN-LAST:event_buscarCiuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Grabar las modificaciones
     

   //     int xx =provincias.buscar(x);
        String n = tLocalidad.getText();
        String m = tCodigoPostal.getText();
        Integer a = Integer.parseInt(tArea.getText());
        Provincias p = (Provincias) jProvincias.getSelectedItem();
        localidad.setNombre(n);
        localidad.setCodarea(a);
        localidad.setCodpostal(Integer.parseInt(m));
        localidad.setProvinciasId(p);
        localidades.edit(localidad);
        this.localidad= new Localidades();
        this.limpiar();
           JOptionPane.showMessageDialog(rootPane, " Se ha grabado la localidad con exito", "Operación exitosa", 1);
        //   System.out.println(xx);
     //      System.out.println("de aca le mando al facade");
          // Provincias p = provincias.find(Integer.parseInt(tProv.getText()));
       /*    resultado = localidades.darAlta(xx, n, Integer.parseInt(m), Integer.parseInt(a));
           //Localidades l = localidades.getLocal();
        if (resultado) {
            JOptionPane.showMessageDialog(rootPane, "La localidad "+n+" ha sido dado de Alta exitosamente", "Operación exitosa", 1);
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR: no se pudo dar de alta la localidad", "ERROR", 0);
        }
        this.limpiar();
*/



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Borra una localidad
        System.out.println("hoalaaa");
        int i = localidad.getId();


         System.out.println(localidad);
         localidad = new Localidades();
       System.out.println(localidad);
         localidades.borrar(i);
          JOptionPane.showMessageDialog(rootPane, "La localidad ha sido borrada exitosamente", "Operación exitosa", 1);      
           this.limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void limpiar() {

      
        tArea.setText("");
       jProvincias.addItem(null);
       tLocalidad.setText("");
        tCodigoPostal.setText("");
         tArea.setText("");
    }
    /**
    * @param args the command line arguments
    */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCiu;
    private javax.swing.JButton buscarProv;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel ciudad;
    private javax.swing.JPanel codigoPostal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox jLocalidades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jProvincias;
    private javax.swing.JTextField tArea;
    private javax.swing.JTextField tCodigoPostal;
    private javax.swing.JTextField tLocalidad;
    // End of variables declaration//GEN-END:variables

}
