/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AtlZona.java
 *
 * Created on 26-nov-2009, 21:11:21
 */

package pantallas;



import entity.Localidades;
import entity.Provincias;
import entity.Zonas;
import java.util.Iterator;
import java.util.List;
import javax.ejb.EJB;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import servers.ServerLocator;
import sessionbeans.LocalidadesFacadeRemote;
import sessionbeans.ProvinciasFacadeRemote;
import sessionbeans.ZonasFacadeRemote;





/**
 *
 * @author Rene
 */
public class AtlZona extends javax.swing.JFrame {
  @EJB
  private static ProvinciasFacadeRemote provincias;
  @EJB
  private static LocalidadesFacadeRemote localidades;
  @EJB
  private static ZonasFacadeRemote zonas;
  private ServerLocator servidor = new ServerLocator();
    private final List<Zonas> lista;
    private Zonas z = new Zonas();

    /** Creates new form AtlZona */
    public AtlZona(List<Zonas> zon) {

        initComponents();

     try{
        provincias = (ProvinciasFacadeRemote) servidor.lookup(ProvinciasFacadeRemote.class.getName());
      }catch(NamingException ex) {
            JOptionPane.showMessageDialog(rootPane, "No se ha podido cargar el Bean  - "+ ex.getMessage() , "ERROR", 2);
            this.dispose();
        }
     try{
        localidades = (LocalidadesFacadeRemote) servidor.lookup(LocalidadesFacadeRemote.class.getName());
      }catch(NamingException ex) {
            JOptionPane.showMessageDialog(rootPane, "No se ha podido cargar el Bean  - "+ ex.getMessage() , "ERROR", 2);
            this.dispose();
        }
     try{
      zonas =  (ZonasFacadeRemote) servidor.lookup(ZonasFacadeRemote.class.getName());
      }catch(NamingException ex) {
            JOptionPane.showMessageDialog(rootPane, "No se ha podido cargar el Bean  - "+ ex.getMessage() , "ERROR", 2);
            this.dispose();
        }
         lista = zon;
          Iterator iter = lista.iterator();
        while (iter.hasNext()){
        Object objeto = iter.next();
        Zonas pro = (Zonas) objeto;
        jZona.addItem(pro);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zona = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDetalle = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLocalidadess = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jProvinciass = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        provincia = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jZona = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta Zona");

        zona.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Zona"));

        jLabel1.setText("Ingrese Zona :");

        tDetalle.setColumns(20);
        tDetalle.setRows(5);
        jScrollPane1.setViewportView(tDetalle);

        jLabel2.setText("Detalles :");

        jLabel3.setText("Localidades :");

        jLabel4.setText("Provincias : ");

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Cargar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zonaLayout = new javax.swing.GroupLayout(zona);
        zona.setLayout(zonaLayout);
        zonaLayout.setHorizontalGroup(
            zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(zonaLayout.createSequentialGroup()
                        .addGroup(zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jProvinciass, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLocalidadess, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zonaLayout.setVerticalGroup(
            zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jProvinciass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(34, 34, 34)
                .addGroup(zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLocalidadess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(32, 32, 32)
                .addGroup(zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        provincia.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincia"));

        jLabel36.setText("Seleccione Zona:");

        jButton4.setText("Cargar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout provinciaLayout = new javax.swing.GroupLayout(provincia);
        provincia.setLayout(provinciaLayout);
        provinciaLayout.setHorizontalGroup(
            provinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provinciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addGap(46, 46, 46)
                .addComponent(jZona, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        provinciaLayout.setVerticalGroup(
            provinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provinciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(provinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Borrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(provincia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Graba o edita una zona

       // z.setNombre(tNombre.getText());
        z.setDetalles(tDetalle.getText());
        Localidades l = (Localidades) jLocalidadess.getSelectedItem();
        z.setLocalidadesid(l);
        zonas.edit(z);
        JOptionPane.showMessageDialog(rootPane, "La zona ha sido dado de Alta exitosamente", "Operación exitosa", 1);
       limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          this.dispose ();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Carga los datos a la pantalla

         z = (Zonas) jZona.getSelectedItem();
        jProvinciass.addItem(z.getLocalidadesid().getProvinciasId());
        jLocalidadess.addItem(z.getLocalidadesid());
        tNombre.setText(z.getNombre());
        tNombre.setEditable(false);
        tDetalle.setText(z.getDetalles());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Carga todas las provincias
       jProvinciass.removeAllItems();// = new javax.swing.JComboBox();
        List<Provincias> lis = provincias.ordenarAsc();
          Iterator iter = lis.iterator();
        while (iter.hasNext()){
        Object objeto = iter.next();
        Provincias pro = (Provincias) objeto;
        jProvinciass.addItem(pro);
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Carga las localidades de una provincias
       jLocalidadess.removeAllItems();// = new javax.swing.JComboBox();
        Provincias p = (Provincias) jProvinciass.getSelectedItem();
        List<Localidades> lo = localidades.buscarLocaProvincia(p);
         Iterator iter = lo.iterator();
        while (iter.hasNext()){
        Object objeto = iter.next();
        Localidades pro = (Localidades) objeto;
        jLocalidadess.addItem(pro);
        }
          
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // borra una zona
        String zon =z.getNombre();
        z= new Zonas();
        zonas.borrar(zon);
        JOptionPane.showMessageDialog(rootPane, "La zona  ha sido borrada exitosamente", "Operación exitosa", 1);
        this.limpiar();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jLocalidadess;
    private javax.swing.JComboBox jProvinciass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jZona;
    private javax.swing.JPanel provincia;
    private javax.swing.JTextArea tDetalle;
    private javax.swing.JTextField tNombre;
    private javax.swing.JPanel zona;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        tNombre.setText("");
        tDetalle.setText("");
        jProvinciass = new javax.swing.JComboBox();
        jLocalidadess = new javax.swing.JComboBox();
    }

}
