/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GProvincias.java
 *
 * Created on 13/06/2010, 14:55:24
 */

package pantallas;



import entity.Provincias;
import java.util.Iterator;
import java.util.List;
import javax.ejb.EJB;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import servers.ServerLocator;
import sessionbeans.ProvinciasFacadeRemote;


/**
 *
 * @author Don Quijote
 */
public class GProvincias extends javax.swing.JFrame {
@EJB
private static ProvinciasFacadeRemote provincias;
private ServerLocator sr = new ServerLocator();
    private List<Provincias> lista;

    /** Creates new form GProvincias */
    public GProvincias() {
        initComponents();
        this.setTitle("Administracion de Provinicias");
                try {
            provincias =  (ProvinciasFacadeRemote) sr.lookup(ProvinciasFacadeRemote.class.getName());
        } catch (NamingException ex) {
                JOptionPane.showMessageDialog(rootPane, "No se ha podido cargar el Bean  - "+ ex.getMessage() , "ERROR", 2);
        }
      this.setAlwaysOnTop(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        tOrden = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre :");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Listar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "PROVINCIAS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("PROVINCIAS");

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ordenar", "Asc", "Desc" }));

        jButton6.setText("Editar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(tOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Graba una provinicia
       boolean resul;
       resul= provincias.darAlta(tNombre.getText());
       if (resul) {
            JOptionPane.showMessageDialog(rootPane, "La provincia "+tNombre.getText()+" ha sido dado grabada exitosamente", "Operación exitosa", 1);
       tNombre.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR: no se pudo dar grabar la provincia", "ERROR", 0);
        }
       this.cargar(provincias.findAll());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Ejecuta unn LIKE que me permite buscar
   /*    int resultado= provincias.buscar(tNombre.getText());
      if(resultado > 0){
         JOptionPane.showMessageDialog(rootPane, tNombre.getText()+" ya esta en la base de datos", "Operación exitosa", 1);
           tNombre.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR: No se encuentra la Provincia", "ERROR", 0);
        }
        List<Provincias> l = provincias.findAlto(tNombre.getText());
       System.out.println(l);
*/

        System.out.println(tOrden.getSelectedItem());
        String orden=(String) tOrden.getSelectedItem();
       lista = provincias.buscar(tNombre.getText(),orden);
       this.cargar(lista);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // listar todo...
        String orden=(String) tOrden.getSelectedItem();
      lista = provincias.listar(orden);
      this.cargar(lista);
        //Integer b = 1;
        //caragar la tabla
        /*      int total =(lista.size());
        Object [][] tab = new Object [total][1];
        int i=0;
        Iterator iter = lista.iterator();
        while (iter.hasNext()){
        //System.out.println(iter.next());
        Object objeto = iter.next();
        pro =  objeto;
        System.out.println(pro.get(b));
        tab[i][0]=pro.get(b);
        b=b+2;
        i++;
        }*/


     /*    List<Provincias> l = provincias.findAll();
        if(l.isEmpty()){
               JOptionPane.showMessageDialog(rootPane, " ya Andaaaa", "Operación exitosa", 1);

        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR: anndaaaaaaaa Provincia", "ERROR", 0);

        }*/

System.out.println( provincias.findAll());
}//GEN-LAST:event_jButton3ActionPerformed
   private void cargar(List<Provincias> lista){
       int total= lista.size();
       Object [][] tab = new Object [total][1];
        int i=0;
       Iterator iter = lista.iterator();
        while (iter.hasNext()){
        Object objeto = iter.next();
            Provincias pro = (Provincias) objeto;
       tab[i][0]=pro.getNombre();
        i++;
      }
jTable1 = new javax.swing.JTable();

jTable1.setModel(new javax.swing.table.DefaultTableModel(
tab,
new String [] {
"Provincias"
}
));
jTable1.setEnabled(true);
 jScrollPane1.setViewportView(jTable1);


   }
        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            // TODO add your handling code here:
            this.dispose ();
        }//GEN-LAST:event_jButton5ActionPerformed

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            // Boton de editar para cambiar
            EditarPro p = new EditarPro(lista);
            p.setVisible(true);
            
        }//GEN-LAST:event_jButton6ActionPerformed
     
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GProvincias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tNombre;
    private javax.swing.JComboBox tOrden;
    // End of variables declaration//GEN-END:variables

}
